<?php
// This file generated by Propel 1.5.4 convert-conf target
return array (
  'BaseThread' => 'orm/om/BaseThread.php',
  'BaseThreadPeer' => 'orm/om/BaseThreadPeer.php',
  'BaseThreadQuery' => 'orm/om/BaseThreadQuery.php',
  'Thread' => 'orm/Thread.php',
  'ThreadPeer' => 'orm/ThreadPeer.php',
  'ThreadQuery' => 'orm/ThreadQuery.php',
  'ThreadTableMap' => 'orm/map/ThreadTableMap.php',
);